<!DOCTYPE paneles [
  <!ELEMENT paneles (evento+)>
  
  <!ELEMENT evento (via, pk, retencion, sentido?, carrilescortados?)>
  <!ATTLIST evento
    tipo CDATA #REQUIRED
    fecha CDATA #IMPLIED
  >

  <!ELEMENT via (nombre, ref, origen, destino, (doble | sentido), carriles)>
  <!ELEMENT doble EMPTY>
  <!ELEMENT sentido (#PCDATA)>

  <!ELEMENT retencion EMPTY>
  <!ATTLIST retencion
    long CDATA #IMPLIED
  >

  <!ELEMENT carrilescortados EMPTY>
  <!ATTLIST carrilescortados
    valor (1|2|3|4) #REQUIRED
  >

  <!ELEMENT pk (#PCDATA)>

  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT ref (#PCDATA)>
  <!ELEMENT origen (#PCDATA)>
  <!ELEMENT destino (#PCDATA)>
  <!ELEMENT carriles (#PCDATA)>
]>

<paneles>
  <evento tipo="Obras" fecha="2024-01-24">
    <via>
      <nombre>M1</nombre>
      <ref>A1</ref>
      <origen>Madrid</origen>
      <destino>Barcelona</destino>
      <doble/>
      <carriles>3</carriles>
    </via>
    <pk>50</pk>
    <retencion long="200"/>
    <carrilescortados valor="3"/>
  </evento>
  <evento tipo="Accidente">
    <via>
      <nombre>A4</nombre>
      <ref>E05</ref>
      <origen>Sevilla</origen>
      <destino>Granada</destino>
      <sentido>Norte</sentido>
      <carriles>2</carriles>
    </via>
    <pk>120</pk>
    <retencion long="150"/>
  </evento>
</paneles>
